#/*Copyright 2020-2021 T-Head Semiconductor Co., Ltd.
#Licensed under the Apache License, Version 2.0.
#*/
#
# 用例: TST-DMA-004 DMA 与 CPU 竞争
# 编译: source ../../sw/setup/setup_env.sh 后,在本目录执行 make
FILE             = dma_004_dma_cpu_race
CPU_ARCH_FLAG_0 ?= e906f
CPU_ARCH_FLAG_1 ?= nodsp
SW_LIB           = ../../sw/lib
include $(SW_LIB)/Makefile
