`define MPSOC_TOP_VIF     tb_top.DUT

`define TX82_CGRA_DV_UT_SYSCTRL_VIF     `MPSOC_TOP_VIF
`define TX82_CGRA_DV_UT_JTAG_VIF     `MPSOC_TOP_VIF
`define TX82_CGRA_DV_UT_UART_VIF     `MPSOC_TOP_VIF
`define TX82_CGRA_DV_UT_GPIO_VIF     `MPSOC_TOP_VIF
`define TX82_CGRA_DV_UT_QSPI_VIF     `MPSOC_TOP_VIF
`define TX82_CGRA_DV_UT_SWITCH_VIF     `MPSOC_TOP_VIF
`define TX82_CGRA_DV_UT_MIIPHY_VIF     `MPSOC_TOP_VIF
`define TX82_CGRA_DV_UT_EFUSE_VIF     `MPSOC_TOP_VIF
