#/*Copyright 2020-2021 T-Head Semiconductor Co., Ltd.
#Licensed under the Apache License, Version 2.0.
#*/
#
# 用例: TST-CPU-001 双核启动与 BOOT ROM 引导
# 编译: source ../../sw/setup/setup_env.sh 后,在本目录执行 make
FILE             = cpu_001_dual_core_boot
CPU_ARCH_FLAG_0 ?= e906f
CPU_ARCH_FLAG_1 ?= nodsp
SW_LIB           = ../../sw/lib
include $(SW_LIB)/Makefile
