#/*Copyright 2020-2021 T-Head Semiconductor Co., Ltd.
#Licensed under the Apache License, Version 2.0.
#*/
#
# 用例: TST-CPU-002 核间中断通信
# 编译: source ../../sw/setup/setup_env.sh 后,在本目录执行 make
FILE             = cpu_002_ipi
CPU_ARCH_FLAG_0 ?= e906f
CPU_ARCH_FLAG_1 ?= nodsp
SW_LIB           = ../../sw/lib
include $(SW_LIB)/Makefile
